language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mnpvVP0licC41mFVhodv2eh9lJXmoI7XQL7bLGor8fAWELULgB8kD/B4bW77eh1SptbhZ0FRyz550Prk46ArXMBS6OQV6Nhd3bLnklUWW4l0PXRcy10ep8xRTcsa08bhoTHiYmcO4atMiuBIFvGOwzHDztqnSH6V3wd3RVirrbTgZWXMt7RiphEVazhHC4k4IuhKtmqKzj2UYuZVkFM3gqS/KNPci+WDMdOvAW3Qj3Y7dqWYOvRJHoVdXkCjl6BX2kYOyWLzh7UncxwZteqUQnghCsP0GfwIQdFDJbv4EceIZClWqCROHqf+PnQ3jfTQ+8nc9J5u3hWlEwAocGSroKEP+glPiw/In8ZvHc0UzcP/sVGwhYrrG7a+rOoVPFKCP/D4w6/5p7QujvQeu4t/f2owg+JdSktZH8qR3XktBqcbzz9iM9RC0FR2E0M1wSaB1S8kRD9Kb7FmkP4QElD4t+AfuCCCediCkSWoMDMCwJV/mHV+rXIMBTFEmG3fMpZ8oc0POR/y4idvdYfy7fdeHaSI2y7V6HBtKN7bkIPu3jQhb+JRxqgDchxbiWJlWTlnQBJrAhJna29IU84HHhQJm47vqyEvH1lpAxaQLTHJ8ioUTcJyVHgUylTYOKQJYX5JBwzh8aoNfgLNOb9NGhVGMYInC3uK87wEjImsYNHSl6s=
  app: glacial-chamber-54154
  on:
    repo: Marjona6/node-shopping-list-integration-tests
